### ISSUE TITLE
Script thinks it unsends messages, it doesn't

### ISSUE THREAD

**Issue by Kados96** [thoughtsunificator/instagram-dm-unsender#30]
Hello,

First of all, thanks for doing this!

The issue: Loads the whole convo perfectly, then even clicks on unsend I think, because just for half a second some panel flashes up, then starts to scroll up. When I manually pause the script, it even states X amount messages unsent.

Problem is, it never actually unsends a message.

**Comment by Kados96** [comment]
![ss](https://github.com/thoughtsunificator/instagram-dm-unsender/assets/136931250/b0ecf85d-5c59-49a3-a4a6-963ef8e37d86)

**Comment by PatoRoxo** [comment]
For me, I click Unsend, it starts scrolling up very slowly saying "retrieving next message" and when it gets to the top of the convo it just stays there still saying that it's retrieving next message. Doesn't start deleting anything.

**Comment by thoughtsunificator** [comment]
I will need full console logs please, to do that you can follow the instructions [here](https://github.com/thoughtsunificator/instagram-dm-unsender/wiki/How-to-export-the-console-logs-of-my-browser).
Lastly, I will also need screenshots of the UI, please take screenshots of the messages (please blur out their content) that fail to unsend.

**Comment by PatoRoxo** [comment]
Tried to run it again and noticed something. It started scrolling to the top very slowly while "retrieving new messages", in the middle it scrolled very quickly for 2 or 3 seconds and then it slowed down again. When it got to the top it just stayed there "retrieving new messages" until i pressed stop processing because it wasn't deleting anything.
Below is the console: 
![console](https://github.com/thoughtsunificator/instagram-dm-unsender/assets/154638951/53672d48-1ea2-4880-9221-ba3a519e737a)
Error with Permissions-Policy header: Unrecognized feature: 'ambient-light-sensor'.
Error with Permissions-Policy header: Unrecognized feature: 'ambient-light-sensor'.
/paid_ads/generete_pixels/?:1 [Report Only] Refused to load the image 'https://www.google.pt/pagead/1p-user-list/858885276/?value=1.00&currency_code=USD&label=qGVACPj3of0DEJyZxpkD&guid=ON&script=0&is_vtc=1&cid=CAQSKQAvHhf_vKHXo-6fADyEEwswkjGWyr70evs-dQzfmmSp5k5kul05vnqu&random=776125336&ipr=y' because it violates the following Content Security Policy directive: "img-src *.instagram.com *.facebook.com *.fbcdn.net data: blob: *.cdninstagram.com *.fbsbx.com android-webview-video-poster: *.giphy.com *.teststagram.com *.igsonar.com *.google-analytics.com *.doubleclick.net *.g.doubleclick.net *.google.com *.google.co.in *.google.co.id *.google.com.br *.google.com.tr *.google.fr *.google.co.uk *.google.ca *.google.co.jp *.google.de *.google.com.mx *.google.es *.google.it *.google.com.ng *.google.com.au *.google.co.kr *.google.com.ar *.google.dz *.google.com.sa *.google.com.tw *.google.nl *.google.com.pk *.googleapis.com *.google.com.vn *.google.cl *.google.co.ma *.google.com.eg *.google.com.co *.google.com.ph *.google.co.il".

/paid_ads/generete_pixels/?:1 Refused to load the image 'https://www.google.pt/pagead/1p-user-list/858885276/?value=1.00&currency_code=USD&label=qGVACPj3of0DEJyZxpkD&guid=ON&script=0&is_vtc=1&cid=CAQSKQAvHhf_vKHXo-6fADyEEwswkjGWyr70evs-dQzfmmSp5k5kul05vnqu&random=776125336&ipr=y' because it violates the following Content Security Policy directive: "img-src *.instagram.com *.facebook.com *.fbcdn.net data: blob: *.cdninstagram.com www.gstatic.com *.fbsbx.com android-webview-video-poster: *.oculuscdn.com www.googleadservices.com *.doubleclick.net *.google.com *.google.co.uk *.giphy.com *.teststagram.com *.igsonar.com *.google-analytics.com *.whatsapp.net *.g.doubleclick.net *.google.co.in *.google.co.id *.google.com.br *.google.com.tr *.google.fr *.google.ca *.google.co.jp *.google.de *.google.com.mx *.google.es *.google.it *.google.com.ng *.google.com.au *.google.co.kr *.google.com.ar *.google.dz *.google.com.sa *.google.com.tw *.google.nl *.google.com.pk *.googleapis.com *.google.com.vn *.google.cl *.google.co.ma *.google.com.eg *.google.com.co *.google.com.ph *.google.co.il".

9Third-party cookie will be blocked. Learn more in the Issues tab.
Error with Permissions-Policy header: Unrecognized feature: 'ambient-light-sensor'.
6default-ui.js:64 Timeout showActionsMenuButton
getNextUIPIMessage @ default-ui.js:64
root-container.e09813a7.js:44 chatbotPort disconnect
root-container.e09813a7.js:44 chatbotPort reconnect
35default-ui.js:64 Timeout showActionsMenuButton
getNextUIPIMessage @ default-ui.js:64
root-container.e09813a7.js:44 chatbotPort disconnect
root-container.e09813a7.js:44 chatbotPort reconnect
root-container.e09813a7.js:44 chatbotPort disconnect
root-container.e09813a7.js:44 chatbotPort reconnect
root-container.e09813a7.js:44 chatbotPort disconnect
root-container.e09813a7.js:44 chatbotPort reconnect
root-container.e09813a7.js:44 chatbotPort disconnect
root-container.e09813a7.js:44 chatbotPort reconnect
root-container.e09813a7.js:44 chatbotPort disconnect
root-container.e09813a7.js:44 chatbotPort reconnect
root-container.e09813a7.js:44 chatbotPort disconnect
root-container.e09813a7.js:44 chatbotPort reconnect
root-container.e09813a7.js:44 chatbotPort disconnect
root-container.e09813a7.js:44 chatbotPort reconnect
default-ui.js:64 Timeout showActionsMenuButton
getNextUIPIMessage @ default-ui.js:64
await in getNextUIPIMessage (async)
getNextUIPIMessage @ uipi.js:49
getNextUIPIMessage @ idmu.js:26
#unsendNextMessage @ unsend-strategy.js:105
run @ unsend-strategy.js:54
#startUnsending @ ui.js:90
#onUnsendThreadMessagesButtonClick @ ui.js:127
(anonymous) @ ui.js:73
default-ui.js:64 DOMException: Aborted: Disconnecting mutation observer...
getNextUIPIMessage @ default-ui.js:64
await in getNextUIPIMessage (async)
getNextUIPIMessage @ uipi.js:49
getNextUIPIMessage @ idmu.js:26
#unsendNextMessage @ unsend-strategy.js:105
run @ unsend-strategy.js:54
#startUnsending @ ui.js:90
#onUnsendThreadMessagesButtonClick @ ui.js:127
(anonymous) @ ui.js:73
root-container.e09813a7.js:44 chatbotPort disconnect
root-container.e09813a7.js:44 chatbotPort reconnect
root-container.e09813a7.js:44 chatbotPort disconnect
root-container.e09813a7.js:44 chatbotPort reconnect
root-container.e09813a7.js:44 chatbotPort disconnect
root-container.e09813a7.js:44 chatbotPort reconnect
root-container.e09813a7.js:44 chatbotPort disconnect
root-container.e09813a7.js:44 chatbotPort reconnect
root-container.e09813a7.js:44 chatbotPort disconnect
root-container.e09813a7.js:44 chatbotPort reconnect
root-container.e09813a7.js:44 chatbotPort disconnect
root-container.e09813a7.js:44 chatbotPort reconnect
root-container.e09813a7.js:44 chatbotPort disconnect
root-container.e09813a7.js:44 chatbotPort reconnect
root-container.e09813a7.js:44 chatbotPort disconnect
root-container.e09813a7.js:44 chatbotPort reconnect
root-container.e09813a7.js:44 chatbotPort disconnect
root-container.e09813a7.js:44 chatbotPort reconnect
root-container.e09813a7.js:44 chatbotPort disconnect
root-container.e09813a7.js:44 chatbotPort reconnect
root-container.e09813a7.js:44 chatbotPort disconnect
root-container.e09813a7.js:44 chatbotPort reconnect
root-container.e09813a7.js:44 chatbotPort disconnect
root-container.e09813a7.js:44 chatbotPort reconnect
root-container.e09813a7.js:44 chatbotPort disconnect
root-container.e09813a7.js:44 chatbotPort reconnect
root-container.e09813a7.js:44 chatbotPort disconnect
root-container.e09813a7.js:44 chatbotPort reconnect
root-container.e09813a7.js:44 chatbotPort disconnect
root-container.e09813a7.js:44 chatbotPort reconnect
root-container.e09813a7.js:44 chatbotPort disconnect
root-container.e09813a7.js:44 chatbotPort reconnect
root-container.e09813a7.js:44 chatbotPort disconnect
root-container.e09813a7.js:44 chatbotPort reconnect
root-container.e09813a7.js:44 chatbotPort disconnect
root-container.e09813a7.js:44 chatbotPort reconnect
root-container.e09813a7.js:44 chatbotPort disconnect
root-container.e09813a7.js:44 chatbotPort reconnect
root-container.e09813a7.js:44 chatbotPort disconnect
root-container.e09813a7.js:44 chatbotPort reconnect
root-container.e09813a7.js:44 chatbotPort disconnect
root-container.e09813a7.js:44 chatbotPort reconnect
root-container.e09813a7.js:44 chatbotPort disconnect
root-container.e09813a7.js:44 chatbotPort reconnect
root-container.e09813a7.js:44 chatbotPort disconnect
root-container.e09813a7.js:44 chatbotPort reconnect
root-container.e09813a7.js:44 chatbotPort disconnect
root-container.e09813a7.js:44 chatbotPort reconnect
root-container.e09813a7.js:44 chatbotPort disconnect
root-container.e09813a7.js:44 chatbotPort reconnect
root-container.e09813a7.js:44 chatbotPort disconnect
root-container.e09813a7.js:44 chatbotPort reconnect
root-container.e09813a7.js:44 chatbotPort disconnect
root-container.e09813a7.js:44 chatbotPort reconnect
root-container.e09813a7.js:44 chatbotPort disconnect
root-container.e09813a7.js:44 chatbotPort reconnect

**Comment by PatoRoxo** [comment]
I ran it again and noticed something. It started scrolling very slowly to the top while retrieving new messages, in the middle it went super fast for like 2 or 3 seconds and then it went slowly again until it reached the top. Then it just stopped while still saying that it  was retrieving new messages so I had to stop the process which showed 0 messages unsent
Below is the console logs:
Error with Permissions-Policy header: Unrecognized feature: 'ambient-light-sensor'.
2RB_AHtkHn7tSX5rp05KwYvfhfrLGla2fTld882OAFaHDfpO9VvNAXg7eJ2ZQtVpt5pdanbe9QJwGAz8GlkhmEk4rIQ8RTqzsOC.js?_nc_x=Ij3Wp8lg5Kz:97 WebSocket connection to 'wss://gateway.instagram.com/ws/realtime?x-dgw-appid=936619743392459&x-dgw-appversion=0&x-dgw-authtype=6%3A0&x-dgw-version=5&x-dgw-uuid=0&x-dgw-tier=prod&x-dgw-app-stream-group=group1' failed: 
a @ 2RB_AHtkHn7tSX5rp05KwYvfhfrLGla2fTld882OAFaHDfpO9VvNAXg7eJ2ZQtVpt5pdanbe9QJwGAz8GlkhmEk4rIQ8RTqzsOC.js?_nc_x=Ij3Wp8lg5Kz:97
2RB_AHtkHn7tSX5rp05KwYvfhfrLGla2fTld882OAFaHDfpO9VvNAXg7eJ2ZQtVpt5pdanbe9QJwGAz8GlkhmEk4rIQ8RTqzsOC.js?_nc_x=Ij3Wp8lg5Kz:39 WebSocket connection to 'wss://edge-chat.instagram.com/chat?sid=2937549802700799&cid=baff5cf8-39d4-4e56-ac48-01c7060f5db7' failed: WebSocket is closed before the connection is established.
b.$14 @ 2RB_AHtkHn7tSX5rp05KwYvfhfrLGla2fTld882OAFaHDfpO9VvNAXg7eJ2ZQtVpt5pdanbe9QJwGAz8GlkhmEk4rIQ8RTqzsOC.js?_nc_x=Ij3Wp8lg5Kz:39
2RB_AHtkHn7tSX5rp05KwYvfhfrLGla2fTld882OAFaHDfpO9VvNAXg7eJ2ZQtVpt5pdanbe9QJwGAz8GlkhmEk4rIQ8RTqzsOC.js?_nc_x=Ij3Wp8lg5Kz:97 WebSocket connection to 'wss://gateway.instagram.com/ws/realtime?x-dgw-appid=936619743392459&x-dgw-appversion=0&x-dgw-authtype=6%3A0&x-dgw-version=5&x-dgw-uuid=0&x-dgw-tier=prod&x-dgw-app-stream-group=group1' failed: 
a @ 2RB_AHtkHn7tSX5rp05KwYvfhfrLGla2fTld882OAFaHDfpO9VvNAXg7eJ2ZQtVpt5pdanbe9QJwGAz8GlkhmEk4rIQ8RTqzsOC.js?_nc_x=Ij3Wp8lg5Kz:97
LAgMsEpAnaO.js?_nc_x=Ij3Wp8lg5Kz:1428 WebSocket connection to 'wss://web-chat-e2ee.facebook.com/ws/chat?ED=CAkICw' failed: 
a @ LAgMsEpAnaO.js?_nc_x=Ij3Wp8lg5Kz:1428
2RB_AHtkHn7tSX5rp05KwYvfhfrLGla2fTld882OAFaHDfpO9VvNAXg7eJ2ZQtVpt5pdanbe9QJwGAz8GlkhmEk4rIQ8RTqzsOC.js?_nc_x=Ij3Wp8lg5Kz:27 WebSocket connection to 'wss://edge-chat.instagram.com/chat?sid=6378577050206207&cid=baff5cf8-39d4-4e56-ac48-01c7060f5db7' failed: 
a @ 2RB_AHtkHn7tSX5rp05KwYvfhfrLGla2fTld882OAFaHDfpO9VvNAXg7eJ2ZQtVpt5pdanbe9QJwGAz8GlkhmEk4rIQ8RTqzsOC.js?_nc_x=Ij3Wp8lg5Kz:27
2RB_AHtkHn7tSX5rp05KwYvfhfrLGla2fTld882OAFaHDfpO9VvNAXg7eJ2ZQtVpt5pdanbe9QJwGAz8GlkhmEk4rIQ8RTqzsOC.js?_nc_x=Ij3Wp8lg5Kz:97 WebSocket connection to 'wss://gateway.instagram.com/ws/realtime?x-dgw-appid=936619743392459&x-dgw-appversion=0&x-dgw-authtype=6%3A0&x-dgw-version=5&x-dgw-uuid=0&x-dgw-tier=prod&x-dgw-app-stream-group=group1' failed: 
a @ 2RB_AHtkHn7tSX5rp05KwYvfhfrLGla2fTld882OAFaHDfpO9VvNAXg7eJ2ZQtVpt5pdanbe9QJwGAz8GlkhmEk4rIQ8RTqzsOC.js?_nc_x=Ij3Wp8lg5Kz:97
LAgMsEpAnaO.js?_nc_x=Ij3Wp8lg5Kz:1428 WebSocket connection to 'wss://web-chat-e2ee.facebook.com/ws/chat?ED=CAkICw' failed: 
a @ LAgMsEpAnaO.js?_nc_x=Ij3Wp8lg5Kz:1428
2RB_AHtkHn7tSX5rp05KwYvfhfrLGla2fTld882OAFaHDfpO9VvNAXg7eJ2ZQtVpt5pdanbe9QJwGAz8GlkhmEk4rIQ8RTqzsOC.js?_nc_x=Ij3Wp8lg5Kz:27 WebSocket connection to 'wss://edge-chat.instagram.com/chat?sid=269054883397631&cid=baff5cf8-39d4-4e56-ac48-01c7060f5db7' failed: 
a @ 2RB_AHtkHn7tSX5rp05KwYvfhfrLGla2fTld882OAFaHDfpO9VvNAXg7eJ2ZQtVpt5pdanbe9QJwGAz8GlkhmEk4rIQ8RTqzsOC.js?_nc_x=Ij3Wp8lg5Kz:27
2RB_AHtkHn7tSX5rp05KwYvfhfrLGla2fTld882OAFaHDfpO9VvNAXg7eJ2ZQtVpt5pdanbe9QJwGAz8GlkhmEk4rIQ8RTqzsOC.js?_nc_x=Ij3Wp8lg5Kz:97 WebSocket connection to 'wss://gateway.instagram.com/ws/realtime?x-dgw-appid=936619743392459&x-dgw-appversion=0&x-dgw-authtype=6%3A0&x-dgw-version=5&x-dgw-uuid=0&x-dgw-tier=prod&x-dgw-app-stream-group=group1' failed: 
a @ 2RB_AHtkHn7tSX5rp05KwYvfhfrLGla2fTld882OAFaHDfpO9VvNAXg7eJ2ZQtVpt5pdanbe9QJwGAz8GlkhmEk4rIQ8RTqzsOC.js?_nc_x=Ij3Wp8lg5Kz:97
LAgMsEpAnaO.js?_nc_x=Ij3Wp8lg5Kz:1428 WebSocket connection to 'wss://web-chat-e2ee.facebook.com/ws/chat?ED=CAkICw' failed: 
a @ LAgMsEpAnaO.js?_nc_x=Ij3Wp8lg5Kz:1428
/ajax/bz?__a=1&__ccg=UNKNOWN&__comet_req=7&__d=www&__hs=19769.HYP%3Ainstagram_web_pkg.2.1..0.1&__hsi=7335988392374728396&__req=t&__rev=1011455605&__s=%3A9oea04%3Aqjakfr&__spin_b=trunk&__spin_r=1011455605&__spin_t=1708042899&__user=0&dpr=1.5&fb_dtsg=NAcM5-5uR_ds30ymn8uSPtHexUiOeVkn1UOge2hdo4G8St7fTV-Fu9g%3A17864721031021537%3A1707955673&jazoest=26235&lsd=ZEo7MJji1ldFaZB-dI4fJH&ph=C3:1 
        
        
       Failed to load resource: net::ERR_NETWORK_CHANGED
/ajax/bz?__a=1&__ccg=UNKNOWN&__comet_req=7&__d=www&__hs=19769.HYP%3Ainstagram_web_pkg.2.1..0.1&__hsi=7335988392374728396&__req=v&__rev=1011455605&__s=l7dlv2%3A9oea04%3Aqjakfr&__spin_b=trunk&__spin_r=1011455605&__spin_t=1708042899&__user=0&dpr=1.5&fb_dtsg=NAcM5-5uR_ds30ymn8uSPtHexUiOeVkn1UOge2hdo4G8St7fTV-Fu9g%3A17864721031021537%3A1707955673&jazoest=26235&lsd=ZEo7MJji1ldFaZB-dI4fJH&ph=C3:1 
        
        
       Failed to load resource: net::ERR_NETWORK_CHANGED
/ajax/bz?__a=1&__ccg=UNKNOWN&__comet_req=7&__d=www&__hs=19769.HYP%3Ainstagram_web_pkg.2.1..0.1&__hsi=7335988392374728396&__req=u&__rev=1011455605&__s=%3A9oea04%3Aqjakfr&__spin_b=trunk&__spin_r=1011455605&__spin_t=1708042899&__user=0&dpr=1.5&fb_dtsg=NAcM5-5uR_ds30ymn8uSPtHexUiOeVkn1UOge2hdo4G8St7fTV-Fu9g%3A17864721031021537%3A1707955673&jazoest=26235&lsd=ZEo7MJji1ldFaZB-dI4fJH&ph=C3:1 
        
        
       Failed to load resource: net::ERR_NETWORK_CHANGED
2RB_AHtkHn7tSX5rp05KwYvfhfrLGla2fTld882OAFaHDfpO9VvNAXg7eJ2ZQtVpt5pdanbe9QJwGAz8GlkhmEk4rIQ8RTqzsOC.js?_nc_x=Ij3Wp8lg5Kz:27 WebSocket connection to 'wss://edge-chat.instagram.com/chat?sid=2151403732598783&cid=baff5cf8-39d4-4e56-ac48-01c7060f5db7' failed: 
a @ 2RB_AHtkHn7tSX5rp05KwYvfhfrLGla2fTld882OAFaHDfpO9VvNAXg7eJ2ZQtVpt5pdanbe9QJwGAz8GlkhmEk4rIQ8RTqzsOC.js?_nc_x=Ij3Wp8lg5Kz:27
2RB_AHtkHn7tSX5rp05KwYvfhfrLGla2fTld882OAFaHDfpO9VvNAXg7eJ2ZQtVpt5pdanbe9QJwGAz8GlkhmEk4rIQ8RTqzsOC.js?_nc_x=Ij3Wp8lg5Kz:97 WebSocket connection to 'wss://gateway.instagram.com/ws/realtime?x-dgw-appid=936619743392459&x-dgw-appversion=0&x-dgw-authtype=6%3A0&x-dgw-version=5&x-dgw-uuid=0&x-dgw-tier=prod&x-dgw-app-stream-group=group1' failed: 
a @ 2RB_AHtkHn7tSX5rp05KwYvfhfrLGla2fTld882OAFaHDfpO9VvNAXg7eJ2ZQtVpt5pdanbe9QJwGAz8GlkhmEk4rIQ8RTqzsOC.js?_nc_x=Ij3Wp8lg5Kz:97
lu1sc3fAwYq.js:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_RESET
RfuOS0lmG0U.js:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_RESET
Nb1n1Dnz-to.js:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_RESET
5VdgSV-eRKa.js:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_RESET
LAgMsEpAnaO.js?_nc_x=Ij3Wp8lg5Kz:1428 WebSocket connection to 'wss://web-chat-e2ee.facebook.com/ws/chat?ED=CAkICw' failed: 
a @ LAgMsEpAnaO.js?_nc_x=Ij3Wp8lg5Kz:1428
/ajax/bz?__a=1&__ccg=UNKNOWN&__comet_req=7&__d=www&__hs=19769.HYP%3Ainstagram_web_pkg.2.1..0.1&__hsi=7335988392374728396&__req=w&__rev=1011455605&__s=l7dlv2%3A9oea04%3Aqjakfr&__spin_b=trunk&__spin_r=1011455605&__spin_t=1708042899&__user=0&dpr=1.5&fb_dtsg=NAcM5-5uR_ds30ymn8uSPtHexUiOeVkn1UOge2hdo4G8St7fTV-Fu9g%3A17864721031021537%3A1707955673&jazoest=26235&lsd=ZEo7MJji1ldFaZB-dI4fJH&ph=C3:1 
        
        
       Failed to load resource: net::ERR_INTERNET_DISCONNECTED
LAgMsEpAnaO.js?_nc_x=Ij3Wp8lg5Kz:1428 WebSocket connection to 'wss://web-chat-e2ee.facebook.com/ws/chat?ED=CAkICw' failed: 
a @ LAgMsEpAnaO.js?_nc_x=Ij3Wp8lg5Kz:1428
LAgMsEpAnaO.js?_nc_x=Ij3Wp8lg5Kz:1428 WebSocket connection to 'wss://web-chat-e2ee.facebook.com/ws/chat?ED=CAkICw' failed: 
a @ LAgMsEpAnaO.js?_nc_x=Ij3Wp8lg5Kz:1428
2RB_AHtkHn7tSX5rp05KwYvfhfrLGla2fTld882OAFaHDfpO9VvNAXg7eJ2ZQtVpt5pdanbe9QJwGAz8GlkhmEk4rIQ8RTqzsOC.js?_nc_x=Ij3Wp8lg5Kz:97 WebSocket connection to 'wss://gateway.instagram.com/ws/realtime?x-dgw-appid=936619743392459&x-dgw-appversion=0&x-dgw-authtype=6%3A0&x-dgw-version=5&x-dgw-uuid=0&x-dgw-tier=prod&x-dgw-app-stream-group=group1' failed: 
a @ 2RB_AHtkHn7tSX5rp05KwYvfhfrLGla2fTld882OAFaHDfpO9VvNAXg7eJ2ZQtVpt5pdanbe9QJwGAz8GlkhmEk4rIQ8RTqzsOC.js?_nc_x=Ij3Wp8lg5Kz:97
2RB_AHtkHn7tSX5rp05KwYvfhfrLGla2fTld882OAFaHDfpO9VvNAXg7eJ2ZQtVpt5pdanbe9QJwGAz8GlkhmEk4rIQ8RTqzsOC.js?_nc_x=Ij3Wp8lg5Kz:97 WebSocket connection to 'wss://gateway.instagram.com/ws/realtime?x-dgw-appid=936619743392459&x-dgw-appversion=0&x-dgw-authtype=6%3A0&x-dgw-version=5&x-dgw-uuid=0&x-dgw-tier=prod&x-dgw-app-stream-group=group1' failed: 
a @ 2RB_AHtkHn7tSX5rp05KwYvfhfrLGla2fTld882OAFaHDfpO9VvNAXg7eJ2ZQtVpt5pdanbe9QJwGAz8GlkhmEk4rIQ8RTqzsOC.js?_nc_x=Ij3Wp8lg5Kz:97
LAgMsEpAnaO.js?_nc_x=Ij3Wp8lg5Kz:1428 WebSocket connection to 'wss://web-chat-e2ee.facebook.com/ws/chat?ED=CAkICw' failed: 
a @ LAgMsEpAnaO.js?_nc_x=Ij3Wp8lg5Kz:1428
LAgMsEpAnaO.js?_nc_x=Ij3Wp8lg5Kz:1428 WebSocket connection to 'wss://web-chat-e2ee.facebook.com/ws/chat?ED=CAkICw' failed: 
a @ LAgMsEpAnaO.js?_nc_x=Ij3Wp8lg5Kz:1428
LAgMsEpAnaO.js?_nc_x=Ij3Wp8lg5Kz:1428 WebSocket connection to 'wss://web-chat-e2ee.facebook.com/ws/chat?ED=CAkICw' failed: 
a @ LAgMsEpAnaO.js?_nc_x=Ij3Wp8lg5Kz:1428
LAgMsEpAnaO.js?_nc_x=Ij3Wp8lg5Kz:1428 WebSocket connection to 'wss://web-chat-e2ee.facebook.com/ws/chat?ED=CAkICw' failed: 
a @ LAgMsEpAnaO.js?_nc_x=Ij3Wp8lg5Kz:1428
LAgMsEpAnaO.js?_nc_x=Ij3Wp8lg5Kz:1428 WebSocket connection to 'wss://web-chat-e2ee.facebook.com/ws/chat?ED=CAkICw' failed: 
a @ LAgMsEpAnaO.js?_nc_x=Ij3Wp8lg5Kz:1428
LAgMsEpAnaO.js?_nc_x=Ij3Wp8lg5Kz:1428 WebSocket connection to 'wss://web-chat-e2ee.facebook.com/ws/chat?ED=CAkICw' failed: 
a @ LAgMsEpAnaO.js?_nc_x=Ij3Wp8lg5Kz:1428
2RB_AHtkHn7tSX5rp05KwYvfhfrLGla2fTld882OAFaHDfpO9VvNAXg7eJ2ZQtVpt5pdanbe9QJwGAz8GlkhmEk4rIQ8RTqzsOC.js?_nc_x=Ij3Wp8lg5Kz:97 WebSocket connection to 'wss://gateway.instagram.com/ws/realtime?x-dgw-appid=936619743392459&x-dgw-appversion=0&x-dgw-authtype=6%3A0&x-dgw-version=5&x-dgw-uuid=0&x-dgw-tier=prod&x-dgw-app-stream-group=group1' failed: 
a @ 2RB_AHtkHn7tSX5rp05KwYvfhfrLGla2fTld882OAFaHDfpO9VvNAXg7eJ2ZQtVpt5pdanbe9QJwGAz8GlkhmEk4rIQ8RTqzsOC.js?_nc_x=Ij3Wp8lg5Kz:97
root-container.e09813a7.js:44 chatbotPort disconnect
root-container.e09813a7.js:44 chatbotPort reconnect
35default-ui.js:64 Timeout showActionsMenuButton
getNextUIPIMessage @ default-ui.js:64
root-container.e09813a7.js:44 chatbotPort disconnect
root-container.e09813a7.js:44 chatbotPort reconnect
root-container.e09813a7.js:44 chatbotPort disconnect
root-container.e09813a7.js:44 
![console](https://github.com/thoughtsunificator/instagram-dm-unsender/assets/154638951/cfc9587c-564f-45fc-aff5-3e7885c91333)

**Comment by thoughtsunificator** [comment]
What is your browser ?

**Comment by PatoRoxo** [comment]
I used Google Chrome with Violentmonkey and version 0.5.18 of the script

**Comment by thoughtsunificator** [comment]
We are missing IDMU's logs, can you enable debug logs and repeat the process you did to export the logs ?

**Comment by FarellNS** [comment]
i have the same issue

**Comment by thoughtsunificator** [comment]
> i have the same issue

Please create another issue and describe your problem there while inluding all details so that I can hopefully solve it.

**Comment by FarellNS** [comment]
Enfaite cava romain haha. J’ai pu lancer avec Mozilla. Y’a des petites astuces genre relancer plusieurs fois et après ça fonctionne.
Souvent y’a juste 5-10 messages max qui se supprime pas mais la c’est facile à la main.
Autre chose que j’ai remarqué, quand la discussion est très courte genre 1 page, généralement ça n’arrive pas à supprimer. Au max ça supprimera 1 seul message.
Je suis sur Mozilla avec le script executor que ta suggérer.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by gitgud5** [comment]
@FarellNS is right. First you gotta run the script, then you just wait for it to stop doing things. Once it has stopped it's process, then I clicked run button again and it started to slowly scroll upwards while deleting any messages that came in its way.

**Comment by thoughtsunificator** [comment]
A new version (v0.5.19) has been released.
