### ISSUE TITLE
Not all Messages are Unsent - Skips All

### ISSUE THREAD

**Issue by Sara-Abo-Shousha** [thoughtsunificator/instagram-dm-unsender#50]
**How impactful is the issue**

(Write your answer here.)

on the first run it unsent some messages, skipped few and unsent some...till it said done.
when i try to rerun it, it goes through the other person messages, option menu appear and skip( cause ofc it can't unsend the other person's messages)
when my messages appear, it skips them and the whole chat and says successfully unsent 1 message when it is done

doesn't unsend all my messages

**How to reproduce the bug**

(Write your answer here.)

**Logs**

[www.instagram.com-1733310985722.log](https://github.com/user-attachments/files/18007122/www.instagram.com-1733310985722.log)

**Screenshots**

(Write your answer here.)

**Desktop (please complete the following information):**

(Write your answer here.)

**Additional context**

(Write your answer here.)

**Comment by Sara-Abo-Shousha** [comment]
tried it on chrome, worse
[www.instagram.com-1733311963758.log](https://github.com/user-attachments/files/18007386/www.instagram.com-1733311963758.log)

**Comment by thoughtsunificator** [comment]
Hello,

Could you give me the following details:

- The version of idmu and your browser 
- The steps to reproduce the issue

**Comment by Sara-Abo-Shousha** [comment]
what do you mean by idmu? if it is the monkey it is Violentmonkey 2.29.0, 
Brave [Version 1.73.91 Chromium: 131.0.6778.85 (Official Build) (64-bit)](https://brave.com/latest/)
 
how to reproduce the issue:
login to instagram web> go to messenger> chat of the person> Monkey extension gives a hint (purple 1) > i click it > chat scrolls automatically>chat go from most recent message from the other person> every message is selected> weird timers appear on every message> too much messages from the other person> it crashes ig> chat scroll automatically without changing> and close after certain time (assuming timeout)

**Comment by upsidedowncity** [comment]
@thoughtsunificator i got this issue too, latest version at 0.5.20

basically, when i run it on a chat, it goes up the messages and deletes some until they stop unsending, but IDMU still goes up the message chain, just that they don't unsend. 

i'm not sure why, but maybe because instagram doesn't allow users to unsend so many and IDMU's requests get blocked in the background.

at the same time, idk if related but at the top when it scrolled all the way to the top and says its done (even only the lower messages were deleted) it says deleted 1 msg

**Comment by upsidedowncity** [comment]
also that fact that the program also considers the messages sent by the other person is extremely time inefficient especially if part of your messages are already deleted but theirs are still there

i tried editing it by changing
`const elements = [...root.querySelectorAll("div[role=row]:not([data-idmu-ignore])")];`
to
`const elements = [...root.querySelectorAll('div[role="row"] div[aria-label="You sent"]')].map(el => el.closest('div[role="row"]'));`
then
`const elements = [...root.querySelectorAll('div[aria-label="You sent"]')].map(el => el.closest('div[role="row"]'));`

but there were glitches, i'm not sure if they were because of my changes or something else like a time out because the program scrolled up for like 30 seconds (the remaining messages were high up) and stopped running before it could get to new messages and said deleted 0

**Comment by thoughtsunificator** [comment]
> also that fact that the program also considers the messages sent by the other person is extremely time inefficient especially if part of your messages are already deleted but theirs are still there
> 
> i tried editing it by changing `const elements = [...root.querySelectorAll("div[role=row]:not([data-idmu-ignore])")];` to `const elements = [...root.querySelectorAll('div[role="row"] div[aria-label="You sent"]')].map(el => el.closest('div[role="row"]'));` then `const elements = [...root.querySelectorAll('div[aria-label="You sent"]')].map(el => el.closest('div[role="row"]'));`
> 
> but there were glitches, i'm not sure if they were because of my changes or something else like a time out because the program scrolled up for like 30 seconds (the remaining messages were high up) and stopped running before it could get to new messages and said deleted 0

Does it occur with all threads? Not all threads are the same, some have images, emoticons etc… Sometimes there are multiple consecutive messages. I need to have an example thread in order to reproduce.

**Comment by upsidedowncity** [comment]
trying to analyze the network requests but i think actions are sent in real time streams

**Comment by thoughtsunificator** [comment]
This is how it goes for me :
![instagram-dm-unsender](https://github.com/user-attachments/assets/b1144d53-c147-440b-b5dd-e55bd1f1a95d)

Unless I have an example thread where IDMU fails to unsend, it will be quite hard for me to do anything.

**Comment by Sara-Abo-Shousha** [comment]
because the thread you have is short in comparison to long chats we are reporting , i tried to record the chat i am having issue with, but i failed to blur the messages contents without blurring the menu chat. my take is, the script is going on the other person's messages for so long that it breaks after 6-10 minutes without unsending a message from my end. my question is why it has to open menu for the other person's message  without initially skipping it if it isn't my message?

**Comment by thoughtsunificator** [comment]
> because the thread you have is short in comparison to long chats we are reporting , i tried to record the chat i am having issue with, but i failed to blur the messages contents without blurring the menu chat. my take is, the script is going on the other person's messages for so long that it breaks after 6-10 minutes without unsending a message from my end. my question is why it has to open menu for the other person's message without initially skipping it if it isn't my message?

What version of IDMU and browser are you using? And what's your OS?
